# Generated by Django 2.2.4 on 2019-11-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, verbose_name='Data Entrega'),
        ),
    ]
