# Generated by Django 2.2.4 on 2019-11-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_auto_20191104_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(null=True, verbose_name='Data Entrega'),
        ),
    ]
