# Generated by Django 2.2.4 on 2019-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_auto_20191104_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(verbose_name='Estado'),
        ),
    ]
